# Generated by Django 5.1 on 2024-09-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0003_borrow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='periode_retal',
        ),
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
        migrations.RemoveField(
            model_name='book',
            name='retal_price',
        ),
        migrations.AddField(
            model_name='book',
            name='available_copies',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='book',
            name='total_copies',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('rental', 'Rented')], max_length=50, null=True),
        ),
    ]
